pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat '"C:\\Users\\saniksud\\Downloads\\apache-maven-3.9.16-bin\\apache-maven-3.9.16\\bin\\mvn.cmd" -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat '"C:\\Users\\saniksud\\Downloads\\apache-maven-3.9.16-bin\\apache-maven-3.9.16\\bin\\mvn.cmd" test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
        steps {
        bat 'call jenkins\\scripts\\deliver.bat'
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
